version: '2'
services:
  reverse_proxy:
    image: jwilder/nginx-proxy
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=default.vhost
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontproxy_default
      - default

  adafruit_forwarder:
    image: brunnel6/dialogflow-adafruit-forwarder
    container_name: adafruit_forwarder
    env_file:
      - ./cred.env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - frontproxy_default
      - default

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  frontproxy_default:
    external: true
